;primeiro comentario


SECTION TEXT
INPUT OLD_DATA
LOAD OLD_DATA
COPY
L1: L2: ADD     ; comentario no meio da instrucao
DIV DOIS        ;dfadsfasd
STORE  NEW_DATA ;fasdfasdfas
MULT DOIS
STORE TMP_DATA ;;;
LOAD OLD_DATA
SUB TMP_DATA
STORE TMP_DAT@A
OUTPUT TMP_DATA dfsfa
COPY NEW_DATA,    OLD_DATA
LOAD		OLD_DATA ; tab indentation
JMPP L1
dasd
STOP

@@@@@

SECTION DATA
DOIS: CONST 2
OLD_DATA: SPACE
NEW_DATA: SPACE
TMP_DATA: SPACE
queijo
/dasçlkksd