E1: EQU 1
SECTION TEXT
INPUT OLD_DATA
LOAD OLD_DATA
IF E1
L1: DIV DOIS        ; 3 = OLD_DATA / 2
STORE  NEW_DATA     ; new_data = 3
MULT DOIS           ; 6 = 3 * 2 
STORE TMP_DATA      ; TMP_DATA = acc (6)
LOAD OLD_DATA       ; acc = OLD_DATA
SUB TMP_DATA + 1        ; OLD_DATA - TMP_DATA
STORE TMP_DATA      ; TMP_DATA = acc (3)
OUTPUT TMP_DATA     ; "0"
COPY NEW_DATA, OLD_DATA ; OLD_DATA = NEW_DATA (3)
LOAD OLD_DATA       ; acc = 3
JMPP L1             ; if acc > 0
S_INPUT TMP_DATA, 5
STOP
SECTION DATA
DOIS: CONST 2
OLD_DATA: SPACE 1
NEW_DATA: SPACE 1
TMP_DATA: SPACE 5